### ISSUE TITLE
prefix-classes does not seem to work

### ISSUE THREAD

**Issue by Samsinite** [gabrielgrant/broccoli-stylus-single#1]
``` stylus
+prefix-classes('foo-')
  .view
    color: red
```

Does not seem to work, which should output:

``` css
.foo-view {
  color: #f00;
}
```
